### ISSUE TITLE
a.pdfViewerAPI.getNextZoomInScale is not a function (caused by "undefined")

### ISSUE THREAD

**Issue by melashkov** [jdryg/angular-pdf-viewer#9]
I am getting very strange error, a.pdfViewerAPI.getNextZoomInScale is not a function (caused by "undefined")

The $scope.pdfViewerAPI = {}; is undefined, 

It works as a demo but when I hook it up to my app I get this error.
I use AngularJS v1.2.15;

**Comment by melashkov** [comment]
pdfViewerAPI was not exposed in viewer, becouse I used ng-if

**Comment by sdhimanwyest** [comment]
I am getting this error. Please help me resolve this.

 file:///android_asset/www/js/libs/angular.min.js: Line 92 : TypeError: Object #<Object> has no method 'getNextZoomInScale'
     at k.$scope.zoomIn (file:///android_asset/www/js/controllers/ProductPdfCtrl.js:86:39)
     at file:///android_asset/www/js/libs/angular.min.js:176:88
     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:65427:9
     at k.$eval (file:///android_asset/www/js/libs/angular.min.js:111:373)
     at k.$apply (file:///android_asset/www/js/libs/angular.min.js:112:121)
     at HTMLButtonElement.<anonymous> (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:65426:13)
     at file:///android_asset/www/js/libs/angular.min.js:31:161
     at q (file:///android_asset/www/js/libs/angular.min.js:7:290)
     at HTMLButtonElement.c (file:///android_asset/www/js/libs/angular.min.js:31:143)
     at triggerMouseEvent (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:2953:7)
